# 数据集相关配置 (将由TrafficStateDataset类使用)
dataset_class: TrafficStateDataset
dataset_config:
  dataset: 'PEMSD4'
  data_path: 'data' # 指向我们项目的数据文件夹
  input_window: 12
  output_window: 12

# 训练相关配置
train:
  epochs: 200
  batch_size: 64
  learning_rate: 0.001
  lambda_guidance: 0.01  # [关键调优参数]
  patience: 20 # 用于早停
  lr_scheduler_args:
    step_size: 20
    gamma: 0.7

# 模型相关配置
model_class: ScaffNet
model_config:
  input_dim: 1
  hidden_dim: 64
  output_dim: 1
  horizon: 12
  scaffold_embedding_dim: 10 